### ISSUE TITLE
vers 0.4.8 - error en la navegación por el menú

### ISSUE THREAD

**Issue by Shut3n** [Paco8/plugin.video.orange.spain#1]
Tras actualizar a la nueva versión del plugin, no entra en los diferentes menús; adjunto el log. En la versión anterior funcionaba la navegación. He vuelto a probar desinstalado el plugin (borrando también la configuración) e instalando desde cero. Tras volver a logearme en el servicio y comprobar, el error persiste.

Kodi.log
> 
> THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'TypeError'>
>                                                    Error Contents: cannot use a string pattern on a bytes-like object
>                                                    Traceback (most recent call last):
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/default.py", line 7, in <module>
>                                                        run()
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/plugin.py", line 514, in run
>                                                        router(sys.argv[2][1:])
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/plugin.py", line 446, in router
>                                                        wl = o.get_wishlist()
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/orange.py", line 397, in get_wishlist
>                                                        t = self.get_title(d)
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/orange.py", line 375, in get_title
>                                                        t['slug'] = self.create_slug(t['info']['title'])
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/orange.py", line 259, in create_slug
>                                                        t = re.sub(r'\W+', '-', t).strip('-')
>                                                      File "/usr/lib/python3.10/re.py", line 209, in sub
>                                                        return _compile(pattern, flags).sub(repl, string, count)
>                                                    TypeError: cannot use a string pattern on a bytes-like object
>                                                    -->End of Python script error report<--
>                                                    
> 2023-02-16 19:03:02.400 T:1763    error <general>: GetDirectory - Error getting plugin://plugin.video.orange.spain/?action=wishlist&type=series
> 2023-02-16 19:03:02.401 T:7       error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orange.spain/?action=wishlist&type=series) failed
> 2023-02-16 19:03:03.016 T:1766  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
> 2023-02-16 19:03:16.562 T:1785     info <general>: Skipped 1 duplicate messages..
> 2023-02-16 19:03:16.562 T:1785    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'TypeError'>
>                                                    Error Contents: cannot use a string pattern on a bytes-like object
>                                                    Traceback (most recent call last):
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/default.py", line 7, in <module>
>                                                        run()
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/plugin.py", line 514, in run
>                                                        router(sys.argv[2][1:])
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/plugin.py", line 446, in router
>                                                        wl = o.get_wishlist()
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/orange.py", line 397, in get_wishlist
>                                                        t = self.get_title(d)
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/orange.py", line 375, in get_title
>                                                        t['slug'] = self.create_slug(t['info']['title'])
>                                                      File "/home/username/.var/app/tv.kodi.Kodi/data/addons/plugin.video.orange.spain/resources/lib/orange.py", line 259, in create_slug
>                                                        t = re.sub(r'\W+', '-', t).strip('-')
>                                                      File "/usr/lib/python3.10/re.py", line 209, in sub
>                                                        return _compile(pattern, flags).sub(repl, string, count)
>                                                    TypeError: cannot use a string pattern on a bytes-like object
>                                                    -->End of Python script error report<--
>                                                    
> 2023-02-16 19:03:16.631 T:1784    error <general>: GetDirectory - Error getting plugin://plugin.video.orange.spain/?action=wishlist&type=series
> 2023-02-16 19:03:16.636 T:7       error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.orange.spain/?action=wishlist&type=series) failed
> 2023-02-16 19:03:17.196 T:1787  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
> 

_KODI 20 - Nexus (Flatpak repository)
OS: Debian Bullseye (GNOME Desktop / Wayland)
Linux x86 64-bit version 5.18.7 (332295)
Kodi (20.0 (20.0.0) Git:20230115-389e701-dirty). Platform: Linux x86 64-bit
Running on Freedesktop.org SDK 22.08 (Flatpak runtime), kernel: Linux x86 64-bit version 5.10.0-21-amd64
CPU: Intel(R) Core(TM)2 Duo CPU     T7500  @ 2.20GHz, 2 cores available
RAM: 4GB
GL_VENDOR = Intel
GL_RENDERER = Mesa Intel(R) 965GM (CL)
GL_VERSION = 2.1 Mesa 22.3.4 (git-a5ffb70f86)_

**Comment by Paco8** [comment]
Gracias por informar del fallo. Creo que está solucionado en la versión 0.4.9.

**Comment by Shut3n** [comment]
Funcionando, gracias😊
