### ISSUE TITLE
Reproducción del contenido en reproductor externo

### ISSUE THREAD

**Issue by alvaroegi** [Paco8/plugin.video.orange.spain#10]
Buenas noches,
He intentado que los canales de Orange se reproduzcan desde un reproductor externo (VLC) ya que cuando intento reproducir contenido en una segunda pantalla mientras en la principal trabajo con otra cosa el reproductor por defecto de Kodi no funciona bien. Con VLC no tengo problemas por eso quería probar con él. Pero, cuando consigo que se abra en el VLC salen pantallazos verdes y difuminados como ocurrían en las televisiones antiguas. Adjunto el archivo playercorefactory.xml por si tiene algún error.
Si lo que pasa es que VLC no es compatible con el formato de streaming, espero que sepais otro reproductor que sí sea compatible y probarlo.
Muchas gracias de antemano.

<?xml version="1.0" encoding="UTF-8"?>
<playercorefactory>
  <players>
    <player name="VLC" type="ExternalPlayer" audio="false" video="true">
		<filename>C:\Program Files (x86)\VideoLAN\VLC\vlc.exe</filename>
		<args>--fullscreen "{1}"</args>
		<hidexbmc>false</hidexbmc>
	</player>
  </players>

  <rules name="system rules">
    <rule name="mms/udp" protocols="mms|mmsh|udp" player="VLC" />
    <rule name="lastfm/shout" protocols="lastfm|shout" player="VLC" />
    <rule name="rtmp" protocols="rtmp" player="VLC" />

    
    <rule name="rtsp" protocols="rtsp" filetypes="!(rm|ra)"  player="VLC" />

    
    <rule name="streams" internetstream="true">
      <rule name="aacp/sdp" mimetypes="audio/aacp|application/sdp" player="VLC" />
      <rule name="mp2" mimetypes="application/octet-stream" filetypes="mp2" player="VLC" />
    </rule>

    
    <rule name="dvd" dvd="true" player="VLC" />
    <rule name="discimage" discimage="true" game="false" player="VLC" />

    
    <rule name="sdp/asf" filetypes="sdp|asf" player="VLC" />

    
    <rule name="nsv" filetypes="nsv" player="VLC" />

    
    <rule name="radio" filetypes="pvr" filename=".*/radio/.*" player="VLC" />
	<rule name="videos" filetypes="mp4" player="VLC" />
	<rule name="all" protocols="*" player="VLC" />
	<rule name="all2" filetypes="*" player="VLC" />

  </rules>
</playercorefactory>

**Comment by Paco8** [comment]
Pues la verdad es que no sé si sería posible usar un reproductor externo porque el contenido de Orange va codificado y es el kodi el que se encarga de descodificarlo.

**Comment by alvaroegi** [comment]
Pues si sabes o alguien sabe alguna forma de poder enviar la señal descodificada a un reproductor externo sería de gran ayuda. Muchas gracias igualmente!

**Comment by joxean943** [comment]
Buenas,
Me he tirado una semana haciendo pruebas con todos los reproductores de video que hay en la Play Store de AndroidTV y alguno más. Al final, he llegado a la conclusión de que es imposible hacer que el Addon OrangeTV de Paco8 funcione con un reproductor externo. Supongo que será por lo que dice su autor sobre la codificación DRM.
Eso sí, debo avisarte de que te has currado un "playercorefactory.xml"  de lo más enrevesado. Si quieres que vlc te reproduzca todo el contenido de Kodi, te vale con la siguiente regla:
<rule filename=".*" player="VLC"/>

Yo, en mi caso, lo he optimizado con otra regla adicional para que me reproduzca con el reproductor nativo los servidores que no pueden reproducirse con VLC:
     <rule filename=".*upstream.*|.*ok.ru.*|.*mycdn.*|.*uqload.*|.*mega.*|.*127.0.0.1.*|.*doodstream.*|.*video-delivery.net.*|.*waaw.*" player="VideoPlayer"/>
     <rule filename=".*" player="VLC"/>

**Comment by joxean943** [comment]
vaya, parece que no puedo poner los códigos porque me los rechaza.
Pego aqui el archivo (para Android)
[playercorefactory.txt](https://github.com/Paco8/plugin.video.orange.spain/files/14864739/playercorefactory.txt)
