### ISSUE TITLE
No funciona la reproducción con VPN

### ISSUE THREAD

**Issue by alvaroegi** [Paco8/plugin.video.orange.spain#16]
Buenas noches, si yo uso una VPN (localizada en España claro), no reproduce ningún vídeo. Es más, si ya estabas reproduciendo uno, este se queda parado hasta que cancelas la VPN.

**Comment by Paco8** [comment]
Supongo que Orange detecta que estás usando una VPN. Yo ahí me temo que no puedo hacer nada.
