### ISSUE TITLE
Obtener keys canales

### ISSUE THREAD

**Issue by nintiendo1** [Paco8/plugin.video.orange.spain#19]
Hola,
ante todo, muchas gracias por tu trabajo.

La verdad que el addon funciona genial. Quiero realizar la misma implementación en otro programa para no depender de Kodi.

Por lo que entiendo, el programa saca las keys de los enlaces de la tv en directo a través del cdm de widevine que te instala en Kodi. Mi duda es como podría ver, al ejecutar un canal a través de tu plugin, cual es la key para yo conocerla. No sé si me he explicado correctamente o si prefieres hablarlo por privado.

Muchas gracias por todo.

**Comment by Paco8** [comment]
No lo sé, el addon le pasa las URLs del manifest y de la licencia al inputstream adaptive, y de todo lo demás ya se encarga inputstream adaptive.

**Comment by nintiendo1** [comment]
Gracias! ¿Y sabes si tiene algún modo debug o similar para saber exactamente lo que está haciendo?

**Comment by Paco8** [comment]
Ya para eso supongo que tendrás que echarle un vistazo al código fuente:
https://github.com/xbmc/inputstream.adaptive
