### ISSUE TITLE
Recomendacion (Recommendation)

### ISSUE THREAD

**Issue by ColibriOS** [Paco8/plugin.video.orange.spain#3]
Es comentarte que el inputstream.adaptive.21.1.0 es el único que veo que funcione en ambos addon  (Movistar+, Orange TV). Los nuevos que han salido si funciona en Orange TV pero no con Movistar+.

It is to tell you that the inputstream.adaptive.21.1.0 is the only one that I see that works in both addons (Movistar+, Orange TV).  The new ones that have come out do work on Orange TV but not with Movistar+.

**Comment by Paco8** [comment]
¿Es esto en kodi 21?

**Comment by ColibriOS** [comment]
> ¿Es esto en kodi 21?



correct if it is on Kodi 21 Omega and kodi 20.1 Nexus after several tests is the solution we have found, use the inputstream.adaptive.21.1.0 for both

**Comment by ManEtha** [comment]
Exacto Paco8 en Kodi Omega 21 Alpha2 ya llevan dos versiones más de Inputstream.Adaptative

https://mirrors.mit.edu/kodi/addons/omega/inputstream.adaptive%2Bandroid-armv7/

la única que funciona en todos los addons es la 21.1.0, pero es que además hay otro problema añadido tanto en Nexus como Omega y es que si tienen instalado el repositorio de Slyguy el InputStream se migra a una versión creada por él totalmente diferente e incompatibie con Skyott, OrangeTV y M+.

Quizá sería buena idea que los addons tuvieran un require a tu repositorio con la versión adecuada de Inputstream

**Comment by Paco8** [comment]
Pues qué raro.
En [este repositorio](https://github.com/Paco8/kodi-repo/blob/master/packages/repository.paco8/repository.paco8-2.0.4.zip?raw=true) tengo una versión de slyguy y los addons de disney+ y hbo max.

**Comment by ManEtha** [comment]
sí, tengo tu repo también instalada tanto en Nexus como en Omega. Con eso no hay problema, el problema es que la nueva versión de Inputstream.adaptative helper de Slyguy te salta como un update de la InputStream.Adaptative de la repo de Kodi oficial y una vez se actualiza tus addons cantan un error porque no tienen definidos el campo "Slyguy". La solución que he tomado yo es subir la versión del Inputstream.Adaptative editando el addon.xml a la 99.9.9 que es superior a la 99...... de la de Slyguy

**Comment by ManEtha** [comment]
Perdona Paco8 el script es:

script.module.inputstreamhelper

que se pasa de la 0.6.1 a la 99.0.5 si tienes instalado el repositorio de Slyguy.

Lo que he hecho como puedes ver es subirle a la 99.9.9 para que me conserve la 0.6.1 de "emilsvennesson, dagwieers, mediaminister, horstle" en lugar de la de Slyguy

**Comment by Paco8** [comment]
He probado a instalar la versión de inputstream helper de Slyguy y efectivamente el addon de orange deja de funcionar, da error al tratar de reproducir cualquier vídeo (los plugins de movistar y skyott siguen funcionando).
En orange se puede solucionar seleccionando un dispositivo SD en "gestionar dispositivos" pero claro, entonces no hay HD.

Parece que esa versión modificada no soporta el tipo de manifiestos (ism) que usa orange.

Mi recomendación es reinstalar el inputstream helper original del repositorio oficial de kodi.

**Comment by ManEtha** [comment]
Eso es lo que hemos hecho, editar las versiones de InputStream.Adaptative en el addon.xml y de InputStream.Helper. En el adaptative hemos cogido los archivos de la 21.1.0 y subido a la 21.1.2 y en el Helper a la 99.9.9 para no renunciar a posibles futuras actualizaciones de addons tanto del repositorio de Kodi como del de Slyguy. La cosa era informarte para que lo supieras por si alguien tiene el mismo problema y se te ocurría alguna solución más profesional.

Gran trabajo con los addons Paco8, van genial tanto en Nexus como en Omega. Un saludo

**Comment by Paco8** [comment]
Creo que el problema del inputstream helper de Slygu ya está solucionado ¿no?

**Comment by ManEtha** [comment]
Por mí sí

**Comment by Paco8** [comment]
Acabo de reportar a los desarrolladores el problema de inputstream adaptative en Kodi 21 con el plugin de orange.

**Comment by Paco8** [comment]
Creo que con esta versión ya vuelven a funcionar otra vez los canales en directo:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-1325/3/artifacts/

**Comment by Paco8** [comment]
Ya ha salido la versión [21.1.3](https://mirrors.mit.edu/kodi/addons/omega/inputstream.adaptive%2Bandroid-armv7/inputstream.adaptive-21.1.3.zip) con el problema de los canales en directo solucionado.
Queda un pequeño problema, y es que con la opción de "subtítulos mejorados" activada, los subtítulos no salen.

**Comment by ManEtha** [comment]
> Ya ha salido la versión [21.1.3](https://mirrors.mit.edu/kodi/addons/omega/inputstream.adaptive%2Bandroid-armv7/inputstream.adaptive-21.1.3.zip) con el problema de los canales en directo solucionado. Queda un pequeño problema, y es que con la opción de "subtítulos mejorados" activada, los subtítulos no salen.

de momento yo sigo con la 21.1.0 y todo perfecto Paco

**Comment by aitornieto71-esp** [comment]
Cuantos dispositivos a la vez puedo ver con orange ?
