### ISSUE TITLE
No funcionan los canales en directo

### ISSUE THREAD

**Issue by Paco8** [Paco8/plugin.video.orange.spain#5]
¿A alguien más le da error al tratar de ver los canales en directo y las grabaciones?

**Comment by Aslaqrt** [comment]
Si, da error al ver los canales

**Comment by Paco8** [comment]
Le he hecho un apaño, no sé si es la solución correcta. Prueba esta versión a ver si te funciona:

[plugin.video.orange.spain-0.7.2.zip](https://github.com/Paco8/plugin.video.orange.spain/files/13052488/plugin.video.orange.spain-0.7.2.zip)

**Comment by Aslaqrt** [comment]
Me sigue sin ir.
Sale este error "Error expecting value: line 1 column 1 (char 0)"

**Comment by Paco8** [comment]
Prueba a reiniciar sesión.

**Comment by Aslaqrt** [comment]
He borrado el addon anterior con los ajustes y todo. He vuelto a iniciar sesión, pero me sale el mismo error.

**Comment by ManuMacarron** [comment]
He hecho la misma prueba, pero sigue apareciendo el mismo error ("Error expecting value: line 1 column 1 (char 0)") al intentar reproducir cualquier canal. 

Lo que hize fuel borrar el addon instalado (0.7.1) y su configuracion en Kodi e instalar todo de nuevo usando el fichero 'plugin.video.orange.spain-0.7.2.zip'. Despues introducir las credenciales otra vez e intentar reproducir cualquier canal sigue dando ese error.

**Comment by ManuMacarron** [comment]
He estado haciendo algunas pruebas más. Me he dado cuenta que algunos de los canales si que abren (solamente unos pocos y ademas casualmente ninguno de los que aparecen en el primer pantallazo por eso no los ví antes). Estos canales que sí que funcionan aparecen marcados de color azul en el [listado](https://i.ibb.co/rpvckHC/image.png).

Esto es lo que aparece en los logs cuando entro el listado  de canales e intento reproducir uno de los que funcionan:

```
2023-10-20 21:13:35.810 T:3612  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-10-20 21:13:40.841 T:4180     info <general>: Skipped 125 duplicate messages..
2023-10-20 21:13:40.841 T:4180    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.orange.spain/?action=play&id=1010&stype=tv&source_type=SmoothStreaming]
2023-10-20 21:13:40.852 T:1100     info <general>: CActiveAESink::OpenSink - initialize sink
``` 

Estos son los logs cuando abro uno de los canales que sí que funcionan:

```
2023-10-20 21:19:58.549 T:4180     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.orange.spain/?action=play&id=1089&stype=tv&source_type=HLS&playback_url=https%3A%2F%2Fapi-ott.runtime.tv%2Floggingmediaurlpassthrough%2Fa.m3u8%3Fversion%3D12%26id%3D2966%26partner%3Dorange
2023-10-20 21:19:59.708 T:6104     info <general>: Creating InputStream
2023-10-20 21:20:00.420 T:6104     info <general>: Creating Demuxer
2023-10-20 21:20:03.736 T:6104     info <general>: Opening stream: 0 source: 256
2023-10-20 21:20:03.736 T:6104     info <general>: Creating video codec with codec id: 27
2023-10-20 21:20:03.736 T:6104     info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2023-10-20 21:20:03.736 T:6104     info <general>: Creating video thread
2023-10-20 21:20:03.736 T:3912     info <general>: running thread: video_thread
2023-10-20 21:20:03.738 T:6104     info <general>: Opening stream: 1 source: 256
2023-10-20 21:20:03.738 T:6104     info <general>: Finding audio codec for: 86018
2023-10-20 21:20:03.738 T:6104     info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2023-10-20 21:20:03.738 T:6104     info <general>: CVideoPlayerAudio::OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2023-10-20 21:20:03.738 T:6104     info <general>: Creating audio thread
2023-10-20 21:20:03.738 T:4036     info <general>: running thread: CVideoPlayerAudio::Process()
2023-10-20 21:20:03.739 T:3912  warning <general>: DXVA::CContext::CreateContext: using app d3d11 device for decoding due extended NV12 shared textures it's not supported.
2023-10-20 21:20:03.739 T:3912  warning <general>: DXVA::CContext::CreateContext: failed to get Video Device and Context.
2023-10-20 21:20:03.739 T:3912     info <general>: DXVA: closing decoder context.
2023-10-20 21:20:03.749 T:4036     info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2023-10-20 21:20:03.749 T:1100     info <general>: CActiveAESink::OpenSink - initialize sink
2023-10-20 21:20:03.751 T:3912     info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2023-10-20 21:20:04.369 T:3912     info <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 39999
```

**Comment by Paco8** [comment]
Los canales en azul usan un sistema diferente (de hecho creo que van en abierto) así que es normal que se vean.
Para los otros canales por lo visto ahora hay que ponerle unos números a la cookie para poder verlos y de momento no he conseguido averiguar de donde salen esos números.

**Comment by perro130** [comment]
Gracias por tu tiempo y trabajo

**Comment by Paco8** [comment]
¿Podéis probar esta versión?

Tras instalarla hay que reiniciar sesión (o cambiar de dispositivo en la opción "gestionar dispositivos"), y después entrar en la lista de canales para que se actualice la cookie.

[plugin.video.orange.spain-0.7.3.zip](https://github.com/Paco8/plugin.video.orange.spain/files/13060877/plugin.video.orange.spain-0.7.3.zip)

**Comment by ManuMacarron** [comment]
> ¿Podéis probar esta versión?
> 
> Tras instalarla hay que reiniciar sesión (o cambiar de dispositivo en la opción "gestionar dispositivos"), y después entrar en la lista de canales para que se actualice la cookie.
> 
> [plugin.video.orange.spain-0.7.3.zip](https://github.com/Paco8/plugin.video.orange.spain/files/13060877/plugin.video.orange.spain-0.7.3.zip)

Con esta versión todo vuleve a funcionar correctamente!
Amazing work! Thank you @Paco8 !

**Comment by davidsotelov** [comment]
Este chico es un crack. Todo vuelve a funcionar de esa manera
Mil gracias

**Comment by Aslaqrt** [comment]
Probado y funcionando. Gracias!

**Comment by davidsotelov** [comment]
Vuelve a salir el mismo error. Como se puede solucionar?
Gracias

**Comment by ManuMacarron** [comment]
> Vuelve a salir el mismo error. Como se puede solucionar? Gracias

Yo tengo instalada la versión 0.7.3 que compartió por aquí y me está funcionando ahora mismo en 2 dispositivos sin problemas.

Probaste a borrar la cuenta de orange y volver a configurarla de nuevo. Probablemente eso pueada ayudar a generar correctamente las cookies necesarias (sin saber mucho como funciona internamente este plugin)

**Comment by ManuMacarron** [comment]
No me dí cuenta de que ya está la version 0.7.4 disponible. Actualizado y funcionando correctamente también.

**Comment by davidsotelov** [comment]
Correcto. 0.7.4 volviendo a meter cuenta y funcionando 
Gracias

**Comment by davidsotelov** [comment]
Hola. Ya no funciona la versión 0.7.6 al menos a mi

**Comment by Paco8** [comment]
¿Da algún error?

**Comment by Paco8** [comment]
¿En qué aparato te ocurre y qué versión de Kodi tienes?

**Comment by Paco8** [comment]
¿Puedes mandar el fichero de registro (kodi.log) para ver exactamente qué error da?

**Comment by Paco8** [comment]
A mí me da un error en smartphone pero no en el firestick, no sé si será el mismo que tienes tú.
Prueba esta versión a ver si te funciona.

[plugin.video.orange.spain-0.7.7.zip](https://github.com/Paco8/plugin.video.orange.spain/files/13588179/plugin.video.orange.spain-0.7.7.zip)

**Comment by llorens89** [comment]
Venía a indicar lo mismo, que había dejado de funcionar. En mi caso, no funcionaba en un chromecast TV (Google TV), un xiaomi MI Stick (android TV)  y el smartphone. En PC y en una tele con android TV integrado sí que funcionaba. 
Con la nueva versión del addon, todo perfecto.

Muchas gracias crack!

**Comment by Ninoh-FOX** [comment]
A mi me ha dejado de funcionar en kodi 18.7 compilado para rpi4 (el unico que me soporta el 5.1) por lo que veo en el registro es un error de python, la version que tiene mi sistema es el 3.7.3 y el 2.7

**Comment by Paco8** [comment]
¿Qué error da?

**Comment by Ninoh-FOX** [comment]
> ¿Qué error da? 

Ahora mismo no se decirte, algo de las lineas de los script de python, ahora te mando log, pero la version 1.7.6 me funciona bien

**Comment by Paco8** [comment]
¿Puedes mirar a ver si esta versión te funciona?

[plugin.video.orange.spain-0.7.8.zip](https://github.com/Paco8/plugin.video.orange.spain/files/13624432/plugin.video.orange.spain-0.7.8.zip)

**Comment by Ninoh-FOX** [comment]
> ¿Puedes mirar a ver si esta versión te funciona?
> 
> [plugin.video.orange.spain-0.7.8.zip](https://github.com/Paco8/plugin.video.orange.spain/files/13624432/plugin.video.orange.spain-0.7.8.zip)
> 

Funciona correctamente. Muchas gracias.

**Comment by davidsotelov** [comment]
Buenas noches. Se me para de vez en cuando. Que configuración me
recomendáis?

**Comment by raiman7** [comment]
Buenas noches, yo cansado de verlo en Chrome, he encontrado el Kodi, pero no se ve bastante igual que por web? quiero decir, creía que se vería como en el deco a 1080 pero por ejemplo con el fútbol se ve bastante mal, hay que configurarlo de alguna manera para maximizar el rendimiento?¿


Un saludo y gracias

**Comment by Paco8** [comment]
Los canales van a 1080p. Mira en la configuración del inputstream adaptive, ahí tienes muchas opciones para elegir la calidad.

**Comment by raiman7** [comment]
Buenas ya lo he mirado, cómo lo tienes tú configurado si no es mucha molestia? a ver es que a mí el fútbol cuando se mueve el balón se ve un poco mal comparado con la televisión, quiero decir se ve mejor en Dazn en la web, que en la web con orange o con Kodi, y seguro que es porque tengo algo mal supongo o es normal ? muchas gracias por responder

**Comment by raiman7** [comment]
Ah bueno eso puede ser, pero en la tv con el deco si que se ve perfecto , quiero decir desde el KODI no puede verse igual que en la tv no? o tendría que poderse? gracias por contestar

**Comment by raiman7** [comment]
La de pruebas 1 la veo pero la M LALIGATV UHD no, solo la puedo ver en la tv con el deco, por web no ni por KODI tampoco, pues tiene que ser lo que dices tú de las imágenes, o que yo tengo algo mal configurado porque lo veo igual que en la web, he puesto aquí un video de como se ve, y 2 fotos de la configuración.
https://github.com/Paco8/plugin.video.orange.spain/assets/153468288/1ecfe53c-a855-404e-b4d3
![foto 1](https://github.com/Paco8/plugin.video.orange.spain/assets/153468288/7addcb3a-8a65-47b6-a1b9-ee37732609e6)
![foto](https://github.com/Paco8/plugin.video.orange.spain/assets/153468288/c11769d3-7fe6-4e2a-bcb2-5381972f320e)
-325c67790402

**Comment by raiman7** [comment]
Me da un error de inicio de sesión con la cuenta, a alguien mas ?

**Comment by Paco8** [comment]
¿Esto? https://github.com/Paco8/plugin.video.orange.spain/issues/6

**Comment by raiman7** [comment]
Ah sí, lo siento no sabía que ya había otro post

Muchas gracias

**Comment by davidrr251980** [comment]
Sabéis si El addon orange tv es compatible con coreelec 9.2.8, pq no consigo que me funcione.
Gracias

**Comment by Paco8** [comment]
> Sabéis si El addon orange tv es compatible con coreelec 9.2.8, pq no consigo que me funcione. Gracias

¿Da algún error?

**Comment by davidrr251980** [comment]
Si, el de inicio de sesion

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by davidrr251980** [comment]
Gracias, me ha funcionado con la versión 10

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by davidsotelov** [comment]
Hola. Tengo 0.8.5 y desde hace días no funciona. Estas ya en ello?
Gracias

**Comment by Paco8** [comment]
Yo no he visto ningún problema.

**Comment by davidsotelov** [comment]
Pues no me funciona ni en android tv ni en firestick

**Comment by Paco8** [comment]
A mí de momento me sigue funcionando en todos los aparatos en que he probado.
¿Te da algún error?
¿Solo fallan los canales en directo?

**Comment by davidsotelov** [comment]
Error al iniciar sesión. He probado a desinstalar y volver a instalar pero
sigue igual por lo q no puedo entrar ni siquiera

**Comment by davidsotelov** [comment]
Creo que el error es que alguien ha cambiado la contraseña sin nosotros
saberlo pq he intentado a través de la app y da error de contraseña
Muchas gracias igualmente

**Comment by davidsotelov** [comment]
Hola Paco
Me pregunto si habría manera de extraer la lista de canales contratados de
Orange tv para utilizarla en alguna app de iptv como estas haciendo con
kodi. Es que tengo algún dispositivo que no me funciona kodi y me gustaría
poder portar mi lista con mi usuario y contraseña para utilizarla en otras
apps
Muchas gracias de antemano

**Comment by Paco8** [comment]
No se puede porque los canales van codificados.
